### ISSUE TITLE
deprecation warning on ruby 1.9.3

### ISSUE THREAD

**Issue by igorbernstein** [monde/mms2r#16]
I don't think any functionality is affected, just wanted to point out that iconv will be deprecated in ruby 1.9.3

`/bundler/gems/mms2r-7a4d0fd419d7/lib/mms2r.rb:62:in 'block in <top (required)>': iconv will be deprecated in the future, use String#encode instead.`

Thanks for a great gem

**Comment by monde** [comment]
I've been wondering what to do about it myself.  Thanks for putting this in an issue for others to see.  We've a bunch of headaches trying to deal with UTF in a manner which is suitable to all.

**Comment by noctivityinc** [comment]
Did you ever come up with a solution for this?  Im using 1.9.3 and Rails 3.2 and definitely have an issue with this requirements.  The warning says to use use String#encode instead.

**Comment by noctivityinc** [comment]
And here is an interesting article that might help: 
http://stackoverflow.com/questions/9126782/how-to-change-deprecated-iconv-to-stringencode-for-invalid-utf8-correction

**Comment by monde** [comment]
thanks for the link, I'll look into this again tonight

**Comment by monde** [comment]
I started hacking on this last night, I've almost completed the refactor that is suitable for Ruby 1.8 and 1.9.  I'm hoping I can release it tonight.

**Comment by noctivityinc** [comment]
Awesome!  Let me know when you want me to test.

Best,

Josh

Joshua Lippiner
Noctivity Inc. 
.: jlippiner@noctivity.com
.: 704-323-5661 tele
.: 310-919-3035 fax

**Comment by monde** [comment]
pushed MMS2R 3.9.0 tonight, let me know how it goes.  I'm running it out in a production app that uses ruby 1.9.3 myself.

**Comment by noctivityinc** [comment]
Seems to work great. Thanks.
