### ISSUE TITLE
Correct Handling of &NBSP; in media['text/plain']

### ISSUE THREAD

**Issue by jpmcgrath** [monde/mms2r#18]
Hey @monde,

Just ran into a small issue with Sprint (again). The issue is that the JSON  returned from the Sprint Ajax is returning &NBSP; instead of a regular space. This causes problems with using ruby string methods like strip as they don't expect the NBSP instead of utf8/ascii.

So, my question is: Should the code I submitted recently be ensuring that the text does not contain the NBSP? Or is this consistent with  other text handling in mms2r i.e. are NBSP also retained/ignored in other parts of the code?

If it is the former let me know and I can send a pull request with a changes that would fix this.

Cheers,

James.

**Comment by monde** [comment]
Add the functionality to account for this scenario and submit a pull request, please.

**Comment by jpmcgrath** [comment]
look for the pull request coming your way.

**Comment by monde** [comment]
released 3.7.1 with fixes and document changes

**Comment by jpmcgrath** [comment]
Thanks mike, love your work!
