### ISSUE TITLE
Verizon text messages aren't parsing properly

### ISSUE THREAD

**Issue by jpmcgrath** [monde/mms2r#20]
I have noticed that MMS2R is no longer parsing verizon text messages correctly. I am getting a partial double up of content. I think that this is because Verizon have changed their email subject line to include a "..." at the end of the subject.

Here is a mail that shows the content of a recent message from vtext:

Return-Path: 7401110000@vtext.com
Received: by 10.229.28.19 with SMTP id k19csp54879qcc; Tue, 26 Jun 2012 11:25:41 -0700
Received: by 10.52.29.179 with SMTP id l19mr9987197vdh.73.1340735141504; Tue, 26 Jun 2012 11:25:41 -0700
Received: from njbrspamp10.vtext.com (njbrspamp11.vtext.com. [69.78.129.156]) by mx.google.com with ESMTP id dr7si10901941vdb.48.2012.06.26.11.25.41; Tue, 26 Jun 2012 11:25:41 -0700
Received: from unknown (HELO njbbvmaapp07-e1) ([10.134.225.138]) by njbrspamp10.vtext.com with ESMTP; Tue, 26 Jun 2012 18:25:41 +0000
Date: Tue, 26 Jun 2012 18:25:41 +0000
From: 7401110000@vtext.com
To: testaddress@gmail.com
Message-ID: 25691599.454593.1340735141169.JavaMail.vmaprod@njbbvmaapp07
Subject: @nextweek great meeting with SocialXXXX, ready to ...
Mime-Version: 1.0
Content-Type: text/plain;
 charset=us-ascii
Content-Transfer-Encoding: 7bit
Delivered-To: testaddress@gmail.com
Received-SPF: pass (google.com: best guess record for domain of
 7401110000@vtext.com designates 69.78.129.156 as permitted sender)
 client-ip=69.78.129.156;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record
 for domain of 7401110000@vtext.com designates 69.78.129.156 as permitted
 sender) smtp.mail=7401110000@vtext.com

@nextweek great meeting with SocialXXXX, ready to kickass #fundayaway

**Comment by monde** [comment]
Thanks for writing this up.  I have some samples I can test out.

**Comment by jpmcgrath** [comment]
Thanks Mike.

**Comment by monde** [comment]
actually, I don't have a current sample of vtext or sprint, can you zip a couple of them up and email them to me?

**Comment by monde** [comment]
closing - issue was with env and not lib

**Comment by jpmcgrath** [comment]
Apologies mike! Issue was between keyboard and seat! Thanks for your assistance in tracking down the source of the problem (i.e. Me!).

Cheers.
