### ISSUE TITLE
Parsing Multipart bodies

### ISSUE THREAD

**Issue by Hyped** [monde/mms2r#4]
New version is working a charm with Mail.  

However I am having a challenge with a couple of messages with the  @media={"text/html".  What method do I use to print out the html version of the text?  Or do I have to open the associated temp file to get at this?

Thanks 
Paul

**Comment by monde** [comment]
The @media is a hash of arrays keyed by content/mime type.  so @media['text/html'] returns an array of file paths that are of that time.  You can enumerate over that array and open each file and process them as you see fit.  See the #default_media and #attachment methods for examples of this strategy.  Their implementation is what I described and they choose the file that is the largest in size.  Post a comment if you get it to work in the way you require and I'll close this out.

**Comment by Hyped** [comment]
This is what I ended up doing.  I know the code isnt very sexy but it works at the moment.
      if ( mms.multipart?  && mms.media.has_key?("text/html"))  
         file = File.open("#{mms.media['text/html']}")  
         while content = file.gets  
            body = body + content  
         end  
         file.close  
      else  
         body = mms.body  
         body.gsub!("\n\r", "<br>")  
         body.gsub!("\n", "<br>")  
      end

**Comment by monde** [comment]
it seems like

file = File.open("#{mms.media['text/html']}")

should at least be
file = File.open("#{mms.media['text/html'].first}")

you should probably enumerate over mms.media['text/html'] that will be an array of filepaths.
