### ISSUE TITLE
 undefined method `return_path' for #<TMail::Mail...

### ISSUE THREAD

**Issue by noctivityinc** [monde/mms2r#5]
Whenever I call MMS2R::Media.new(email) I get the following with the latest version of the gem:

NoMethodError: undefined method `return_path' for #<TMail::Mail:0x1068155b8>
/Users/jlippiner/.rvm/gems/ree-1.8.7-2010.01@tdt/gems/mms2r-3.0.1/lib/mms2r/media.rb:169:in`domain'
/Users/jlippiner/.rvm/gems/ree-1.8.7-2010.01@tdt/gems/mms2r-3.0.1/lib/mms2r/media.rb:153:in `create'
/Users/jlippiner/.rvm/gems/ree-1.8.7-2010.01@tdt/gems/mms2r-3.0.1/lib/mms2r/media.rb:111:in`new'

**Comment by noctivityinc** [comment]
FYI - I DO have the mail gem installed and I am requiring it right before im requiring mms2r

**Comment by noctivityinc** [comment]
Was passing it an old TMail object.  Sorry.

**Comment by outofcuriosity** [comment]
I'm also having this problem, any ideas?

**Comment by vladexologija** [comment]
Tmail does not have return_path method. What object should we pass to MMS2R::Media.new for mail.return_path to work? 
I'm having this problem also. Tried updating tmail gem but does not work.
