### ISSUE TITLE
Problems with ruby 1.9.2 and rails3

### ISSUE THREAD

**Issue by mcculloughsean** [monde/mms2r#6]
I'm trying out the example script that comes with the code. It runs (with some appropriate modifications) in Ruby 1.8.7 and Rails2. However under Ruby 1.9.7 and rails 3 it fails. Here's the dump:
/Users/seanmccullough/.rvm/gems/ruby-1.9.2-preview3@rails3/gems/mms2r-3.0.1/lib/mms2r/media.rb:188:in `domain': undefined method`any?' for "vzwpix.com":String (NoMethodError)
    from /Users/seanmccullough/.rvm/gems/ruby-1.9.2-preview3@rails3/gems/mms2r-3.0.1/lib/mms2r/media.rb:153:in `create'
    from /Users/seanmccullough/.rvm/gems/ruby-1.9.2-preview3@rails3/gems/mms2r-3.0.1/lib/mms2r/media.rb:111:in`new'
    from mmstest.rb:7:in `<main>'

The relevant code:

 media.rb line 169
when mail.return_path
          mail.return_path ? mail.return_path.split('@').last : ''
        else
          ''
        end
line 188
        when return_path.any?

it seems that when the return path is nil, it tries to call 
    ''.any?
which doesn't exist.

I'm not sure why this happens under one version of ruby and not another.

**Comment by monde** [comment]
coincidently I'm working on a 3.1.0 release today, I'll address this, thanks

**Comment by mcculloughsean** [comment]
great, thanks

**Comment by monde** [comment]
I have a bunch of carrier updates that I'm going to put into 3.1.0, the character encoding issues for Ruby 1.9.2 is a pain in the ass.  I see that Lawrence Curtis has been tackling this on this own, perhaps I can cherry pick his work http://github.com/slipstreamstudio/mms2r

I'll make 3.2.0 a Ruby 1.9.2 compatibility release, I'm hoping to get 3.1.0 out tonight, and 3.2.0 out next week.

**Comment by mcculloughsean** [comment]
Thanks for the heads up. 
I've run into some other compatibility issues with Ruby 1.9.2 and Rails3 so for the time being i'm just staying with Rails2
