### ISSUE TITLE
Mail/MMS2R

### ISSUE THREAD

**Issue by mcculloughsean** [monde/mms2r#7]
I've been having some strange things happen with some multipart messages. 

The message is: http://gist.github.com/472080

and the stack trace is: 

```
/usr/local/lib/ruby/gems/1.8/gems/mail-2.2.4/lib/mail/field.rb:122:in `send': undefined    method `filename' for #<Mail::UnstructuredField:0x1020051b0> (NoMethodError)
from /usr/local/lib/ruby/gems/1.8/gems/mail-2.2.4/lib/mail/field.rb:122:in `method_missing'
from /usr/local/lib/ruby/gems/1.8/gems/mail-2.2.4/lib/mail/message.rb:1849:in `find_attachment'
from /usr/local/lib/ruby/gems/1.8/gems/mms2r-3.0.1/lib/mail_ext.rb:33:in `filename'
from /usr/local/lib/ruby/gems/1.8/gems/mms2r-3.0.1/lib/mms2r/media.rb:507:in `filename?'
from /usr/local/lib/ruby/gems/1.8/gems/mms2r-3.0.1/lib/mms2r/media.rb:471:in `temp_file'
from /usr/local/lib/ruby/gems/1.8/gems/mms2r-3.0.1/lib/mms2r/media.rb:405:in `process_media'
from /usr/local/lib/ruby/gems/1.8/gems/mms2r-3.0.1/lib/mms2r/media.rb:358:in `process'
from /usr/local/lib/ruby/gems/1.8/gems/mms2r-3.0.1/lib/mms2r/media.rb:355:in `each'
from /usr/local/lib/ruby/gems/1.8/gems/mms2r-3.0.1/lib/mms2r/media.rb:355:in `process'
from /usr/local/lib/ruby/gems/1.8/gems/mms2r-3.0.1/lib/mms2r/media.rb:233:in `initialize'
from /usr/local/lib/ruby/gems/1.8/gems/mms2r-3.0.1/lib/mms2r/media.rb:113:in `orig_new'
from /usr/local/lib/ruby/gems/1.8/gems/mms2r-3.0.1/lib/mms2r/media.rb:113:in `new'
from mmstest.rb:7
```

It seems like it doesn't like dealing with this kind of multipart message. Anyone else run into this issue, and have a fix for it?

**Comment by monde** [comment]
I can reproduce this in MMS2R 3.0.1 and 3.1.0 and I have the latest Mail 2.2.5 gem.

There have been recent changes to the Mail gem, I'll double check that mms2r-3.0.1/lib/mail_ext.rb is still compatible with the recent Mail changes.

**Comment by monde** [comment]
It's an issue with the Mail gem, see:
http://github.com/mikel/mail/issues/#issue/82

**Comment by monde** [comment]
I took a copy of your sample and changed the lines 43, 44, 69, 71 from:

Content-Disposition: INLINE
Content-Type: TEXT/HTML;
Content-Disposition: INLINE;
Content-Type: IMAGE/JPEG;

to

Content-Disposition: inline
Content-Type: text/html;
Content-Disposition: inline;
Content-Type: image/jpeg;

and Mail processed the file correctly.
