### ISSUE TITLE
default_media is nil

### ISSUE THREAD

**Issue by dbora** [monde/mms2r#8]
Hi,

I am using the example code off of the main project page.  I have MMS2R 3.1 and Mail 2.2.5 installed.  When I run this code:

  mail = MMS2R::Media.new(Mail.read('./test.video-tmobile.eml'))

mail.default_media is nil and mail.media an empty Hash.  I've been troubleshooting this for a couple of days and I'm not making much progress.  Let me know if you need to see the .eml file, it's rather large and I'd rather not junk up this post with that content.

Thanks

**Comment by dbora** [comment]
Sorry, here is the file:

https://gist.github.com/ad020f47116a90421a67

**Comment by monde** [comment]
I'm not sure why you are getting this error, I was able to process the file and play the video, see this skitch:
http://skitch.com/monde/dc6y1/24-06-10-0828.mpeg

Are you certain the mail file is being opened?  I suppose that Mail would raise an error if not.  Probably not related but Mail has been having issues lately as well, see:
http://github.com/monde/mms2r/issues#issue/7

**Comment by dbora** [comment]
Yes, I'm actually debugging the script in Eclipse and other vars are populated correctly, like @carrier mail.body, headers, etc.  

Have you tried to run the your sample code with my file?

**Comment by monde** [comment]
Yes, that was with you file, I just named it differently, if you look at the skitch I took http://skitch.com/monde/dc6y1/24-06-10-0828.mpeg you will see I'm playing your mpeg.

**Comment by dbora** [comment]
Oh, sorry about that!  You're using 2.2.5 of Mail and 3.1 of mms2r?

**Comment by monde** [comment]
Here is my console output
https://gist.github.com/fcb4c920417ba213e0ed

**Comment by monde** [comment]
yes, latest gems mms2r 3.1.0 and Mail 2.2.5

**Comment by dbora** [comment]
Ignore that last post, I had to do some fuddling around with Nokogiri but here is the error free (and unfortunately content free) run of the same command you used:

http://gist.github.com/479983

**Comment by monde** [comment]
I don't know what to tell you, I can't reproduce your issue.  I'm able to decode an open your 24-06-10_0828.mpeg in the Ruby environment on my MacBook at work, and just now on my personal laptop with Ubuntu.  Is it just this one file, or all of your files?  If it's all of your mail/mms files then something is not right in your developer environment and I've done all I can do to help you at this point.

**Comment by dbora** [comment]
Agreed, thanks for your help.  I'm going to try and get this on an Ubuntu env.  

Thanks for all your help.

**Comment by monde** [comment]
You might try deleting the first blank line as well.  When you do a save-as from source on gmail it adds annoying empty blank line at the top which makes the file (technically) malformed.  TMail would choke on this.

**Comment by dbora** [comment]
The version of the file I have has no blank line.  I did have a version of the file with a leading blank line and it choked right away and very specifically.
