### ISSUE TITLE
mms2r 2.4.1/ Tmail and application/octet-stream

### ISSUE THREAD

**Issue by tranquiliste** [monde/mms2r#9]
Hello,

I am using mms2r/tmail with my rails application to process email received and I am very happy with it.
Today one of my user encountered a weird problem where 2 attached .pdf files were not process. I looked at the source of the mail and they both had a "application/octet-stream" type.

looking at the code in media.rb I noticed that on the process_media method  (lines 404 to 426) if I comment the test on the 'application/octet-stream' to just keep the line 416 
"type = part.content_type"
it works correctly and the 2 pdf files are processed

Do you have any idea on what's happened?

Thanks in advance
Nicolas

**Comment by monde** [comment]
Hi Nicolas

Send me a zipped up sample to mikemondragon@gmail.com or post it up in a gist so I can copy into my development environment and investigate the issue you've uncovered.

Even better would be for you to fork MMS2R.  Resolve the issue you've uncovered, write tests for your solution, and then send me a merge request.

Thanks
Mike
